global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "host"
    static_configs:
      - targets: ["host.docker.internal:9100"] # For node_exporter on host


  # Add more scrape configurations as needed
  # Example for Docker metrics:
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['host.docker.internal:9323']
